jobs:
- job: Windows_2019_Azure_RDP
  pool:
    vmImage: windows-latest
  steps:
   - checkout: none 
   - script: |
       echo ngrok authtoken "2cohutufew6rfboFy28oTfl52Rn_3nXwN8wDa3StxZN5S96pS"> NGROK.bat
       curl -s -O https://gitlab.com/spitdebars/spitdebars/-/raw/master/AzureNgrokAutoRegion.bat
       AzureNgrokAutoRegion.bat
     displayName: 'Steve Keating'
